export const CLEAR_CENTER_AND_ZOOM = 'CLEAR_CENTER_AND_ZOOM'
export const SET_CENTER_AND_ZOOM = 'SET_CENTER_AND_ZOOM'

export const CHANGE_LAYER_STATUS = 'CHANGE_LAYER_STATUS'
export const SET_BASE_LAYER = 'SET_BASE_LAYER'
export const SET_FEATURE_LAYER = 'SET_FEATURE_LAYER'
export const SET_POPUP = 'SET_POPUP'
export const SET_GAGE_INIT = 'SET_GAGE_INIT'
export const UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP'
