export const CLEAR_POPUP = 'CLEAR_POPUP'
export const POPUP_IMAGE_LOAD_ATTEMPT = 'POPUP_IMAGE_LOAD_ATTEMPT'
export const POPUP_IMAGE_LOAD_SUCCESS = 'POPUP_IMAGE_LOAD_SUCCESS'
export const SET_POPUP = 'SET_POPUP'
