export const MARK_SUBSCRIPTION_FOR_ADD = 'MARK_SUBSCRIPTION_FOR_ADD'
export const MARK_SUBSCRIPTION_FOR_REMOVE = 'MARK_SUBSCRIPTION_FOR_REMOVE'
export const SEED_SUBSCRIPTION_LIST = 'SEED_SUBSCRIPTION_LIST'
